import Head from 'next/head'
import Image from 'next/image'
import Layout from '../src/components/layout'
//import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <Layout>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <h2>Home Page</h2>
      <br />
      <p>
Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...
      </p>
    </Layout>
  )
}
